<script setup lang="ts">
import { ref } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import { errorMessage, request, operationId, type FitnessObject, type Receipt } from '../../lib/api'
import { useSession } from '../../stores/session'
const session = useSession(); const error = ref(''); const busy = ref(false); const operations = ref<Receipt[]>([]); const preference = ref(''); const preferenceObject = ref<FitnessObject | null>(null)
async function load() { if (!session.loggedIn) return; try { operations.value = (await request<{ items: Receipt[] }>('/api/v1/operations')).items; const items = (await request<{ items: FitnessObject[] }>('/api/v1/objects?limit=100')).items; preferenceObject.value = items.find(item => item.kind === 'coaching_preference') || null; preference.value = String(preferenceObject.value?.payload.text || '') } catch (e) { error.value = errorMessage(e) } }
onShow(load)
async function start() { busy.value = true; error.value = ''; try { await session.startDevelopmentSession(); await load() } catch (e) { error.value = errorMessage(e) } finally { busy.value = false } }
function loginWechat() { uni.login({ provider: 'weixin', success(result) { if (!result.code) { error.value = '微信登录没有完成，请再试一次。'; return }; busy.value = true; request<{ access_token: string; user_id: string }>('/api/v1/auth/wechat-login?code=' + encodeURIComponent(result.code), 'POST').then(session.acceptSession).then(load).catch(e => { error.value = errorMessage(e) }).finally(() => { busy.value = false }) }, fail: () => { error.value = '微信登录暂时不可用，请稍后再试。' } }) }
async function savePreference() { const text = preference.value.trim(); if (!text) { error.value = '可以写下你的习惯或期待，也可以暂时不填写。'; return }; busy.value = true; error.value = ''; const id = operationId(); const change = preferenceObject.value ? { action: 'replace', object_id: preferenceObject.value.id, expected_version: preferenceObject.value.version, payload: { ...preferenceObject.value.payload, text } } : { action: 'create', kind: 'coaching_preference', payload: { text } }; try { await request('/api/v1/agent-actions/apply', 'POST', { operation_id: id, operations: [change] }, id); await load(); uni.showToast({ title: '偏好已保存', icon: 'success' }) } catch (e) { error.value = errorMessage(e) } finally { busy.value = false } }
async function exportData() { busy.value = true; error.value = ''; try { const data = await request<Record<string, unknown>>('/api/v1/me/export'); uni.setClipboardData({ data: JSON.stringify(data, null, 2), success: () => uni.showModal({ title: '内容已复制', content: '你的 FitMind 数据已复制到剪贴板，请粘贴到安全位置保存。', showCancel: false }) }) } catch (e) { error.value = errorMessage(e) } finally { busy.value = false } }
function deleteAccount() { uni.showModal({ title: '确定删除全部数据？', content: '记录、计划、对话和操作历史都会被删除，且无法恢复。', confirmText: '永久删除', confirmColor: '#a43f31', success: async result => { if (!result.confirm) return; busy.value = true; error.value = ''; try { await request('/api/v1/me?confirmation=' + encodeURIComponent('永久删除我的FitMind数据'), 'DELETE'); session.clearSession(); operations.value = []; preference.value = ''; preferenceObject.value = null; uni.showToast({ title: '数据已删除', icon: 'success' }) } catch (e) { error.value = errorMessage(e) } finally { busy.value = false } } }) }
</script>
<template><view class="page"><view class="eyebrow">FITMIND</view><view class="title">我的</view><view class="subtitle">管理登录、教练偏好和你的数据。</view><view class="card"><view class="label">登录 FitMind</view><view v-if="!session.loggedIn" class="body">登录后，你的记录、计划和对话会在下次打开时继续保留。</view><button v-if="!session.loggedIn" class="primary" style="margin-top: 26rpx" :loading="busy" :disabled="busy" @tap="loginWechat">使用微信登录</button><button v-if="!session.loggedIn" class="ghost" style="margin-top: 14rpx" :loading="busy" :disabled="busy" @tap="start">本机体验</button><view v-else class="hint">已登录，可以开始记录和与教练交流。</view><view v-if="error" class="error">{{ error }}</view></view><template v-if="session.loggedIn"><view class="card"><view class="label">告诉教练你的习惯</view><view class="muted">用自己的话描述偏好即可，例如：希望建议简短一些；我不确定时先问我；周末更容易安排训练。</view><textarea v-model="preference" maxlength="4000" placeholder="写下你希望教练了解的事情（可以留空）" /><button class="secondary" :loading="busy" :disabled="busy || !preference.trim()" @tap="savePreference">保存偏好</button></view><view class="card"><view class="label">交流方式</view><view class="body">只有你主动发送消息时，教练才会回应。离开小程序后不会收到催促通知。</view></view><view class="subtitle" style="margin-top: 32rpx">数据管理</view><view class="row"><button class="secondary" :disabled="busy" @tap="exportData">导出我的数据</button><button class="ghost danger" :disabled="busy" @tap="deleteAccount">删除全部数据</button></view><view class="subtitle" style="margin-top: 32rpx">最近保存</view><view v-if="!operations.length" class="empty">还没有保存操作。</view><view v-for="item in operations" :key="item.operation_id" class="card"><view class="body">已保存 {{ item.objects.length }} 项内容</view><view v-for="object in item.objects" :key="object.id" class="muted">{{ object.kind === 'activity' ? '训练记录' : object.kind === 'plan' ? '训练计划' : '个人偏好' }} · 第 {{ object.version }} 版</view></view></template></view></template>
